service:
  name: line-facial-deviation-value-ts

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  environment: ${file(./conf/env.yml)}
custom:
  defaultStage: dev
  defaultProfile: sls

functions:
  webhook:
    handler: handler.webhook
    timeout: 10
    events:
      - http:
          method: post
          path: webhook
