service:
  name: line-facial-deviation-value-ts

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: sls

functions:
  hello:
    handler: handler.hello
    timeout: 10
    environment: ${file(./conf/env.yml)}
    events:
      - http:
          method: post
          path: webhook
